/**
 * @file ui_assets.c
 * @brief Embedded HTML UI assets compiled directly into the firmware image.
 *
 * @details
 *  - UI_INDEX_HTML   — WiFi setup portal, served at GET /.
 *  - UI_LOCATIONS_HTML — Location management UI, served at GET /locations.
 *
 * @note clang-format is disabled for this file to preserve the HTML string
 *       literal formatting. The content is intentionally not reformatted.
 */

//------------------------------------------------------------------------------
// private includes
//------------------------------------------------------------------------------

#include "ui/ui_assets.h"

// clang-format off
const char UI_INDEX_HTML[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<title>ESP32 Setup — kochcoding</title>\n"
    "<style>\n"
    "  @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Sora:wght@300;400;600;700&display=swap');\n"
    "  :root {\n"
    "    --blue-primary: #367EDA;\n"
    "    --blue-light: #58B2E9;\n"
    "    --blue-mid: #408CDE;\n"
    "    --blue-accent: #52AAE7;\n"
    "    --bg-deep: #0d0f14;\n"
    "    --bg-card: #13161d;\n"
    "    --bg-input: #1a1e28;\n"
    "    --border: rgba(54,126,218,0.18);\n"
    "    --text-primary: #f0f2f7;\n"
    "    --text-muted: #6b7694;\n"
    "    --text-dim: #3d4560;\n"
    "    --success: #3dd68c;\n"
    "    --error: #f04f5a;\n"
    "    --warning: #f0a04f;\n"
    "  }\n"
    "  *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n"
    "  html,body{height:100%;background:var(--bg-deep);color:var(--text-primary);font-family:'Sora',sans-serif;-webkit-font-smoothing:antialiased;overflow-x:hidden}\n"
    "  body::before{content:'';position:fixed;inset:0;background-image:linear-gradient(rgba(54,126,218,0.04) 1px,transparent 1px),linear-gradient(90deg,rgba(54,126,218,0.04) 1px,transparent 1px);background-size:40px 40px;pointer-events:none;z-index:0}\n"
    "  body::after{content:'';position:fixed;top:-20%;right:-10%;width:60vw;height:60vw;background:radial-gradient(circle,rgba(54,126,218,0.08) 0%,transparent 70%);pointer-events:none;z-index:0;animation:orb-drift 8s ease-in-out infinite alternate}\n"
    "  @keyframes orb-drift{from{transform:translate(0,0)}to{transform:translate(-5%,5%)}}\n"
    "  .wrapper{position:relative;z-index:1;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:24px 16px}\n"
    "  .header{width:100%;max-width:420px;margin-bottom:28px;display:flex;flex-direction:column;align-items:flex-start;gap:10px;animation:slide-down 0.6s cubic-bezier(0.16,1,0.3,1) both}\n"
    "  @keyframes slide-down{from{opacity:0;transform:translateY(-16px)}to{opacity:1;transform:translateY(0)}}\n"
    "  .logo-svg{width:160px;height:auto;opacity:0.92}\n"
    "  .header-top{width:100%;display:flex;align-items:center;justify-content:space-between}\n"
    "  .lang-toggle{display:flex;background:rgba(255,255,255,0.04);border:1px solid var(--border);border-radius:4px;overflow:hidden}\n"
    "  .lang-btn{padding:4px 10px;background:none;border:none;color:var(--text-muted);cursor:pointer;font-family:'DM Mono',monospace;font-size:11px;font-weight:500;letter-spacing:0.05em;transition:all 0.2s}\n"
    "  .lang-btn.active{background:var(--blue-primary);color:#fff}\n"
    "  .header-sub{font-size:11px;font-weight:400;letter-spacing:0.18em;text-transform:uppercase;color:var(--text-muted);font-family:'DM Mono',monospace}\n"
    "  .card{width:100%;max-width:420px;background:var(--bg-card);border:1px solid var(--border);border-radius:16px;padding:32px;position:relative;overflow:hidden;animation:slide-up 0.7s cubic-bezier(0.16,1,0.3,1) 0.1s both}\n"
    "  @keyframes slide-up{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}\n"
    "  .card::before{content:'';position:absolute;top:0;left:0;right:0;height:1px;background:linear-gradient(90deg,transparent,var(--blue-primary),var(--blue-light),transparent);opacity:0.7}\n"
    "  .card-title{font-size:18px;font-weight:600;color:var(--text-primary);margin-bottom:4px;letter-spacing:-0.01em}\n"
    "  .card-desc{font-size:13px;color:var(--text-muted);margin-bottom:28px;line-height:1.5}\n"
    "  .field{margin-bottom:16px}\n"
    "  .field label{display:block;font-size:11px;font-weight:600;letter-spacing:0.12em;text-transform:uppercase;color:var(--text-muted);font-family:'DM Mono',monospace;margin-bottom:8px}\n"
    "  .input-wrap{position:relative}\n"
    "  .field input{width:100%;background:var(--bg-input);border:1px solid var(--border);border-radius:10px;padding:13px 16px;font-size:14px;font-family:'DM Mono',monospace;color:var(--text-primary);outline:none;transition:border-color 0.2s,box-shadow 0.2s,background 0.2s;-webkit-appearance:none}\n"
    "  .field input::placeholder{color:var(--text-dim)}\n"
    "  .field input:focus{border-color:var(--blue-primary);box-shadow:0 0 0 3px rgba(54,126,218,0.12);background:#1e2330}\n"
    "  .field input.error{border-color:var(--error);box-shadow:0 0 0 3px rgba(240,79,90,0.1)}\n"
    "  .pass-toggle{position:absolute;right:14px;top:50%;transform:translateY(-50%);background:none;border:none;cursor:pointer;color:var(--text-muted);padding:4px;display:flex;align-items:center;transition:color 0.2s}\n"
    "  .pass-toggle:hover{color:var(--text-primary)}\n"
    "  #pass{padding-right:44px}\n"
    "  .btn-submit{width:100%;margin-top:24px;padding:14px 24px;background:linear-gradient(135deg,var(--blue-primary),var(--blue-mid));border:none;border-radius:10px;color:#fff;font-size:14px;font-weight:600;font-family:'Sora',sans-serif;letter-spacing:0.02em;cursor:pointer;position:relative;overflow:hidden;transition:opacity 0.2s,transform 0.15s,box-shadow 0.2s;box-shadow:0 4px 20px rgba(54,126,218,0.25)}\n"
    "  .btn-submit:hover:not(:disabled){opacity:0.92;transform:translateY(-1px);box-shadow:0 6px 28px rgba(54,126,218,0.35)}\n"
    "  .btn-submit:active:not(:disabled){transform:translateY(0)}\n"
    "  .btn-submit:disabled{opacity:0.5;cursor:not-allowed}\n"
    "  .btn-submit .btn-spinner{display:none}\n"
    "  .btn-submit.loading .btn-text{display:none}\n"
    "  .btn-submit.loading .btn-spinner{display:flex;align-items:center;justify-content:center;gap:8px}\n"
    "  .spinner-dot{width:6px;height:6px;border-radius:50%;background:rgba(255,255,255,0.9);animation:bounce 0.9s ease-in-out infinite}\n"
    "  .spinner-dot:nth-child(2){animation-delay:0.15s}\n"
    "  .spinner-dot:nth-child(3){animation-delay:0.30s}\n"
    "  @keyframes bounce{0%,80%,100%{transform:scale(0.6);opacity:0.4}40%{transform:scale(1);opacity:1}}\n"
    "  .status{margin-top:16px;border-radius:10px;padding:12px 16px;font-size:13px;line-height:1.5;display:none;align-items:flex-start;gap:10px;animation:fade-in 0.3s ease both}\n"
    "  @keyframes fade-in{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:translateY(0)}}\n"
    "  .status.show{display:flex}\n"
    "  .status.success{background:rgba(61,214,140,0.08);border:1px solid rgba(61,214,140,0.25);color:var(--success)}\n"
    "  .status.error{background:rgba(240,79,90,0.08);border:1px solid rgba(240,79,90,0.25);color:var(--error)}\n"
    "  .status.connecting{background:rgba(54,126,218,0.08);border:1px solid rgba(54,126,218,0.25);color:var(--blue-accent)}\n"
    "  .status-icon{flex-shrink:0;margin-top:1px}\n"
    "  .sta-status{margin-top:20px;padding-top:20px;border-top:1px solid var(--border);display:flex;align-items:center;gap:10px;font-size:12px;color:var(--text-muted);font-family:'DM Mono',monospace}\n"
    "  .sta-dot{width:7px;height:7px;border-radius:50%;flex-shrink:0;background:var(--text-dim)}\n"
    "  .sta-dot.connected{background:var(--success);box-shadow:0 0 6px var(--success)}\n"
    "  .sta-dot.connecting{background:var(--warning);animation:pulse 1.2s ease-in-out infinite}\n"
    "  .sta-dot.failed{background:var(--error)}\n"
    "  @keyframes pulse{0%,100%{opacity:1}50%{opacity:0.3}}\n"
    "  .footer{margin-top:24px;font-size:11px;color:var(--text-dim);font-family:'DM Mono',monospace;text-align:center;letter-spacing:0.05em;animation:slide-up 0.7s cubic-bezier(0.16,1,0.3,1) 0.25s both}\n"
    "  @media(max-width:480px){.card{padding:24px 20px;border-radius:12px}.card-title{font-size:16px}}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"wrapper\">\n"
    "  <div class=\"header\">\n"
    "    <div class=\"header-top\">\n"
    "      <svg class=\"logo-svg\" viewBox=\"0 0 449 207\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"
    "        <path d=\"M63.5983 205.5H0.598328L37.5983 0.5H98.5983L86.5983 69.5H87.5983L166.598 0.5H240.598L134.598 96.5V98L241.598 205.5H157.598L78.5983 123.5H77.5983L63.5983 205.5Z\" fill=\"white\" stroke=\"#A3A1A3\"/>\n"
    "        <path d=\"M448.598 205.5V206.5L357.598 205.5L303.598 152.5V151.5H389.598L448.598 205.5Z\" fill=\"#3677DB\"/>\n"
    "        <path d=\"M250.598 98.5L264.598 112.5L262.598 113.5L238.598 134.5H209.598L250.598 98.5Z\" fill=\"#3A7ADA\"/>\n"
    "        <path d=\"M171.598 98.5L208.598 135.5L250.598 98.5L300.598 54.5H378.598L438.598 0.5H279.598L229.598 45.5L199.598 72.5L188.598 81.5L171.598 97.5V98.5Z\" fill=\"url(#sg0)\"/>\n"
    "        <path d=\"M209.598 134.5L208.598 135.5L279.598 205.5H357.598L303.598 152.5V151.5L264.598 112.5L262.598 113.5L238.598 134.5H209.598Z\" fill=\"url(#sg1)\"/>\n"
    "        <defs>\n"
    "          <linearGradient id=\"sg0\" x1=\"305.098\" y1=\"0.5\" x2=\"305.098\" y2=\"135.5\" gradientUnits=\"userSpaceOnUse\">\n"
    "            <stop stop-color=\"#408CDE\"/><stop offset=\"1\" stop-color=\"#58B2E9\"/>\n"
    "          </linearGradient>\n"
    "          <linearGradient id=\"sg1\" x1=\"283.098\" y1=\"112.5\" x2=\"283.098\" y2=\"205.5\" gradientUnits=\"userSpaceOnUse\">\n"
    "            <stop stop-color=\"#52AAE7\"/><stop offset=\"1\" stop-color=\"#479FE5\"/>\n"
    "          </linearGradient>\n"
    "        </defs>\n"
    "      </svg>\n"
    "      <div class=\"lang-toggle\">\n"
    "        <button class=\"lang-btn\" onclick=\"setLang('de')\">DE</button>\n"
    "        <button class=\"lang-btn active\" onclick=\"setLang('en')\">EN</button>\n"
    "      </div>\n"
    "    </div>\n"
    "    <span class=\"header-sub\" id=\"lbl-sub\">Device Setup</span>\n"
    "  </div>\n"
    "  <div class=\"card\">\n"
    "    <div class=\"card-title\" id=\"lbl-title\">WiFi Configuration</div>\n"
    "    <div class=\"card-desc\" id=\"lbl-desc\">Connect your device to a local network to enable cloud features and remote access.</div>\n"
    "    <div class=\"field\">\n"
    "      <label for=\"ssid\" id=\"lbl-ssid\">Network Name (SSID)</label>\n"
    "      <input id=\"ssid\" type=\"text\" placeholder=\"Your WiFi network\" maxlength=\"31\" autocomplete=\"off\" autocapitalize=\"none\" spellcheck=\"false\">\n"
    "    </div>\n"
    "    <div class=\"field\">\n"
    "      <label for=\"pass\" id=\"lbl-pass\">Password</label>\n"
    "      <div class=\"input-wrap\">\n"
    "        <input id=\"pass\" type=\"password\" placeholder=\"Network password\" maxlength=\"63\" autocomplete=\"current-password\">\n"
    "        <button class=\"pass-toggle\" type=\"button\" onclick=\"togglePass()\" aria-label=\"Toggle password visibility\">\n"
    "          <svg id=\"eye-icon\" width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
    "            <path d=\"M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z\"/>\n"
    "            <circle cx=\"12\" cy=\"12\" r=\"3\"/>\n"
    "          </svg>\n"
    "        </button>\n"
    "      </div>\n"
    "    </div>\n"
    "    <button class=\"btn-submit\" id=\"btn\" onclick=\"submitWifi()\">\n"
    "      <span class=\"btn-text\" id=\"lbl-btn\">Connect Device</span>\n"
    "      <span class=\"btn-spinner\">\n"
    "        <span class=\"spinner-dot\"></span>\n"
    "        <span class=\"spinner-dot\"></span>\n"
    "        <span class=\"spinner-dot\"></span>\n"
    "      </span>\n"
    "    </button>\n"
    "    <div class=\"status success\" id=\"status-success\">\n"
    "      <span class=\"status-icon\">\n"
    "        <svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"20 6 9 17 4 12\"/></svg>\n"
    "      </span>\n"
    "      <span id=\"status-success-text\">Credentials saved. Connecting to network...</span>\n"
    "    </div>\n"
    "    <div class=\"status error\" id=\"status-error\">\n"
    "      <span class=\"status-icon\">\n"
    "        <svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\"/><line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\"/></svg>\n"
    "      </span>\n"
    "      <span id=\"status-error-text\">An error occurred. Please try again.</span>\n"
    "    </div>\n"
    "    <div class=\"status connecting\" id=\"status-connecting\">\n"
    "      <span class=\"status-icon\">\n"
    "        <svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M1.42 9a16 16 0 0 1 21.16 0\"/><path d=\"M5 12.55a11 11 0 0 1 14.08 0\"/><path d=\"M10.54 15.64a6 6 0 0 1 2.92 0\"/><circle cx=\"12\" cy=\"20\" r=\"1\"/></svg>\n"
    "      </span>\n"
    "      <span id=\"lbl-connecting\">Attempting to connect. This may take a few seconds...</span>\n"
    "    </div>\n"
    "    <div class=\"sta-status\" id=\"sta-status\">\n"
    "      <div class=\"sta-dot\" id=\"sta-dot\"></div>\n"
    "      <span id=\"sta-text\">Checking connection status...</span>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"footer\">ESP32 Core v0.1.0 &nbsp;&middot;&nbsp; kochcoding &nbsp;&middot;&nbsp; <a href=\"/locations\" style=\"color:var(--text-dim);text-decoration:none\" onmouseover=\"this.style.color='var(--blue-accent)'\" onmouseout=\"this.style.color='var(--text-dim)'\">Orte</a></div>\n"
    "</div>\n"
    "<script>\n"
    "  var T = {\n"
    "    en: {\n"
    "      sub:        'Device Setup',\n"
    "      title:      'WiFi Configuration',\n"
    "      desc:       'Connect your device to a local network to enable cloud features and remote access.',\n"
    "      ssid:       'Network Name (SSID)',\n"
    "      pass:       'Password',\n"
    "      btn:        'Connect Device',\n"
    "      ssidPh:     'Your WiFi network',\n"
    "      passPh:     'Network password',\n"
    "      connecting: 'Attempting to connect. This may take a few seconds...',\n"
    "      errSsid:    'Please enter a network name (SSID).',\n"
    "      errGeneric: 'An error occurred. Please try again.',\n"
    "      errReach:   'Could not reach device. Are you connected to ESP32-Core-Setup?',\n"
    "      errDevice:  'Device returned an error. Please try again.',\n"
    "      savedMsg:   function(s){return 'Credentials saved. Connecting to \"'+s+'\"...'},\n"
    "      connected:  function(ip){return 'Connected · '+(ip||'')},\n"
    "      conneting2: 'Connecting to network...',\n"
    "      failed:     'Connection failed — check credentials',\n"
    "      notConn:    'Not connected',\n"
    "      checking:   'Checking connection status...',\n"
    "    },\n"
    "    de: {\n"
    "      sub:        'Geräte-Setup',\n"
    "      title:      'WLAN-Konfiguration',\n"
    "      desc:       'Verbinde dein Gerät mit einem lokalen Netzwerk, um Cloud-Funktionen und Fernzugriff zu aktivieren.',\n"
    "      ssid:       'Netzwerkname (SSID)',\n"
    "      pass:       'Passwort',\n"
    "      btn:        'Gerät verbinden',\n"
    "      ssidPh:     'Dein WLAN-Netzwerk',\n"
    "      passPh:     'Netzwerkpasswort',\n"
    "      connecting: 'Verbindungsversuch läuft. Das kann einige Sekunden dauern...',\n"
    "      errSsid:    'Bitte Netzwerknamen (SSID) eingeben.',\n"
    "      errGeneric: 'Ein Fehler ist aufgetreten. Bitte erneut versuchen.',\n"
    "      errReach:   'Gerät nicht erreichbar. Bist du mit ESP32-Core-Setup verbunden?',\n"
    "      errDevice:  'Gerät hat einen Fehler zurückgegeben. Bitte erneut versuchen.',\n"
    "      savedMsg:   function(s){return 'Zugangsdaten gespeichert. Verbinde mit \"'+s+'\"...'},\n"
    "      connected:  function(ip){return 'Verbunden · '+(ip||'')},\n"
    "      conneting2: 'Verbindet mit Netzwerk...',\n"
    "      failed:     'Verbindung fehlgeschlagen — Zugangsdaten prüfen',\n"
    "      notConn:    'Nicht verbunden',\n"
    "      checking:   'Verbindungsstatus wird geprüft...',\n"
    "    }\n"
    "  };\n"
    "  var lang = 'en';\n"
    "\n"
    "  function setLang(l) {\n"
    "    lang = l;\n"
    "    localStorage.setItem('kc_lang', l);\n"
    "    document.querySelectorAll('.lang-btn').forEach(function(b){\n"
    "      b.classList.toggle('active', b.textContent === l.toUpperCase());\n"
    "    });\n"
    "    applyLang();\n"
    "  }\n"
    "\n"
    "  function applyLang() {\n"
    "    var t = T[lang];\n"
    "    document.getElementById('lbl-sub').textContent        = t.sub;\n"
    "    document.getElementById('lbl-title').textContent      = t.title;\n"
    "    document.getElementById('lbl-desc').textContent       = t.desc;\n"
    "    document.getElementById('lbl-ssid').textContent       = t.ssid;\n"
    "    document.getElementById('lbl-pass').textContent       = t.pass;\n"
    "    document.getElementById('lbl-btn').textContent        = t.btn;\n"
    "    document.getElementById('lbl-connecting').textContent = t.connecting;\n"
    "    document.getElementById('ssid').placeholder           = t.ssidPh;\n"
    "    document.getElementById('pass').placeholder           = t.passPh;\n"
    "    document.getElementById('sta-text').textContent       = t.checking;\n"
    "  }\n"
    "\n"
    "  function togglePass(){\n"
    "    var i=document.getElementById('pass'),e=document.getElementById('eye-icon'),h=i.type==='password';\n"
    "    i.type=h?'text':'password';\n"
    "    e.innerHTML=h?'<path d=\"M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94\"/><path d=\"M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19\"/><line x1=\"1\" y1=\"1\" x2=\"23\" y2=\"23\"/>':'<path d=\"M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/>';\n"
    "  }\n"
    "  function hideAll(){\n"
    "    ['status-success','status-error','status-connecting'].forEach(function(id){document.getElementById(id).classList.remove('show');});\n"
    "  }\n"
    "  function showStatus(type,msg){\n"
    "    hideAll();\n"
    "    var el=document.getElementById('status-'+type);\n"
    "    if(msg&&type!=='connecting'){document.getElementById('status-'+type+'-text').textContent=msg;}\n"
    "    el.classList.add('show');\n"
    "  }\n"
    "  function updateStaStatus(state,ip){\n"
    "    var t=T[lang];\n"
    "    var dot=document.getElementById('sta-dot'),text=document.getElementById('sta-text');\n"
    "    dot.className='sta-dot';\n"
    "    if(state==='connected'){dot.classList.add('connected');text.textContent=t.connected(ip);}\n"
    "    else if(state==='connecting'){dot.classList.add('connecting');text.textContent=t.conneting2;}\n"
    "    else if(state==='failed'){dot.classList.add('failed');text.textContent=t.failed;}\n"
    "    else{text.textContent=t.notConn;}\n"
    "  }\n"
    "  function pollStatus(){\n"
    "    fetch('/api/config/wifi')\n"
    "      .then(function(r){return r.json();})\n"
    "      .then(function(d){updateStaStatus(d.sta_state,d.ip);})\n"
    "      .catch(function(){updateStaStatus('idle');});\n"
    "  }\n"
    "  function submitWifi(){\n"
    "    var t=T[lang];\n"
    "    var ssid=document.getElementById('ssid').value.trim();\n"
    "    var pass=document.getElementById('pass').value;\n"
    "    var btn=document.getElementById('btn');\n"
    "    document.getElementById('ssid').classList.remove('error');\n"
    "    if(!ssid){document.getElementById('ssid').classList.add('error');showStatus('error',t.errSsid);return;}\n"
    "    btn.classList.add('loading');btn.disabled=true;\n"
    "    hideAll();showStatus('connecting');\n"
    "    fetch('/api/config/wifi',{\n"
    "      method:'POST',\n"
    "      headers:{'Content-Type':'application/json'},\n"
    "      body:JSON.stringify({ssid:ssid,pass:pass})\n"
    "    })\n"
    "    .then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json();})\n"
    "    .then(function(d){\n"
    "      btn.classList.remove('loading');btn.disabled=false;\n"
    "      if(d.ok){\n"
    "        showStatus('success',t.savedMsg(ssid));\n"
    "        updateStaStatus('connecting');\n"
    "        setTimeout(pollStatus,3000);setTimeout(pollStatus,6000);setTimeout(pollStatus,10000);\n"
    "      }else{showStatus('error',t.errDevice);}\n"
    "    })\n"
    "    .catch(function(){\n"
    "      btn.classList.remove('loading');btn.disabled=false;\n"
    "      showStatus('error',t.errReach);\n"
    "    });\n"
    "  }\n"
    "  document.addEventListener('keydown',function(e){if(e.key==='Enter')submitWifi();});\n"
    "  (function(){var s=localStorage.getItem('kc_lang');if(s==='de'||s==='en'){setLang(s);}})();\n"
    "  pollStatus();\n"
    "  setInterval(pollStatus,15000);\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";

const char UI_LOCATIONS_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"de\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "<title>kochcoding // Orte</title>\n"
    "<style>\n"
    "  @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;700&family=Syne:wght@400;700;800&display=swap');\n"
    "\n"
    "  :root {\n"
    "    --bg:        #0d0f14;\n"
    "    --bg2:       #13161d;\n"
    "    --bg3:       #1a1e28;\n"
    "    --border:    rgba(54,126,218,0.18);\n"
    "    --accent:    #408CDE;\n"
    "    --accent2:   #367EDA;\n"
    "    --accent3:   #52AAE7;\n"
    "    --danger:    #ff4455;\n"
    "    --text:      #e0e0e0;\n"
    "    --text-muted:#888;\n"
    "    --mono:      'JetBrains Mono', monospace;\n"
    "    --display:   'Syne', sans-serif;\n"
    "  }\n"
    "\n"
    "  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
    "\n"
    "  body {\n"
    "    background: var(--bg);\n"
    "    color: var(--text);\n"
    "    font-family: var(--mono);\n"
    "    font-size: 13px;\n"
    "    min-height: 100vh;\n"
    "    line-height: 1.6;\n"
    "  }\n"
    "  body::before{content:'';position:fixed;inset:0;background-image:linear-gradient(rgba(54,126,218,0.04) 1px,transparent 1px),linear-gradient(90deg,rgba(54,126,218,0.04) 1px,transparent 1px);background-size:40px 40px;pointer-events:none;z-index:0}\n"
    "  body::after{content:'';position:fixed;top:-20%;right:-10%;width:60vw;height:60vw;background:radial-gradient(circle,rgba(54,126,218,0.08) 0%,transparent 70%);pointer-events:none;z-index:0;animation:orb-drift 8s ease-in-out infinite alternate}\n"
    "  @keyframes orb-drift{from{transform:translate(0,0)}to{transform:translate(-5%,5%)}}\n"
    "\n"
    "  /* ── HEADER ── */\n"
    "  header {\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    justify-content: space-between;\n"
    "    padding: 16px 24px;\n"
    "    border-bottom: 1px solid var(--border);\n"
    "    background: var(--bg2);\n"
    "    position: sticky;\n"
    "    top: 0;\n"
    "    z-index: 100;\n"
    "    position: sticky;\n"
    "  }\n"
    "\n"
    "  .logo {\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    gap: 10px;\n"
    "  }\n"
    "  .logo svg {\n"
    "    height: 32px;\n"
    "    width: auto;\n"
    "  }\n"
    "\n"
    "\n"
    "  .header-right {\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    gap: 12px;\n"
    "  }\n"
    "\n"
    "  .back-link {\n"
    "    color: var(--text-muted);\n"
    "    text-decoration: none;\n"
    "    font-size: 12px;\n"
    "    letter-spacing: 0.05em;\n"
    "    transition: color 0.2s;\n"
    "  }\n"
    "  .back-link:hover { color: var(--accent); }\n"
    "\n"
    "  .lang-toggle {\n"
    "    display: flex;\n"
    "    background: var(--bg3);\n"
    "    border: 1px solid var(--border);\n"
    "    border-radius: 4px;\n"
    "    overflow: hidden;\n"
    "  }\n"
    "  .lang-btn {\n"
    "    padding: 4px 10px;\n"
    "    background: none;\n"
    "    border: none;\n"
    "    color: var(--text-muted);\n"
    "    cursor: pointer;\n"
    "    font-family: var(--mono);\n"
    "    font-size: 11px;\n"
    "    font-weight: 500;\n"
    "    letter-spacing: 0.05em;\n"
    "    transition: all 0.2s;\n"
    "  }\n"
    "  .lang-btn.active {\n"
    "    background: var(--accent);\n"
    "    color: var(--bg);\n"
    "  }\n"
    "\n"
    "  /* ── MAIN LAYOUT ── */\n"
    "  main {\n"
    "    max-width: 1100px;\n"
    "    margin: 0 auto;\n"
    "    padding: 24px 16px 48px;\n"
    "    position: relative;\n"
    "    z-index: 1;\n"
    "  }\n"
    "\n"
    "  /* ── SECTION TITLE ── */\n"
    "  .section-label {\n"
    "    font-size: 10px;\n"
    "    letter-spacing: 0.15em;\n"
    "    text-transform: uppercase;\n"
    "    color: var(--accent);\n"
    "    margin-bottom: 12px;\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    gap: 8px;\n"
    "  }\n"
    "  .section-label::after {\n"
    "    content: '';\n"
    "    flex: 1;\n"
    "    height: 1px;\n"
    "    background: var(--border);\n"
    "  }\n"
    "\n"
    "  /* ── LOCATION MANAGEMENT ── */\n"
    "  #mgmt-section { margin-bottom: 36px; }\n"
    "\n"
    "  .add-form {\n"
    "    display: grid;\n"
    "    grid-template-columns: 1fr 120px 120px auto;\n"
    "    gap: 8px;\n"
    "    margin-bottom: 16px;\n"
    "  }\n"
    "  @media (max-width: 600px) {\n"
    "    .add-form { grid-template-columns: 1fr 1fr; }\n"
    "    .add-form .btn-add { grid-column: 1 / -1; }\n"
    "  }\n"
    "\n"
    "  input[type=\"text\"], input[type=\"number\"] {\n"
    "    background: var(--bg2);\n"
    "    border: 1px solid var(--border);\n"
    "    color: var(--text);\n"
    "    font-family: var(--mono);\n"
    "    font-size: 13px;\n"
    "    padding: 8px 12px;\n"
    "    border-radius: 4px;\n"
    "    outline: none;\n"
    "    transition: border-color 0.2s;\n"
    "  }\n"
    "  input[type=\"text\"]:focus, input[type=\"number\"]:focus {\n"
    "    border-color: var(--accent);\n"
    "  }\n"
    "  input::placeholder { color: var(--text-muted); }\n"
    "\n"
    "  .btn {\n"
    "    font-family: var(--mono);\n"
    "    font-size: 12px;\n"
    "    font-weight: 500;\n"
    "    letter-spacing: 0.05em;\n"
    "    padding: 8px 16px;\n"
    "    border-radius: 4px;\n"
    "    border: none;\n"
    "    cursor: pointer;\n"
    "    transition: all 0.15s;\n"
    "    white-space: nowrap;\n"
    "  }\n"
    "  .btn-add {\n"
    "    background: var(--accent);\n"
    "    color: var(--bg);\n"
    "  }\n"
    "  .btn-add:hover { background: var(--accent2); }\n"
    "  .btn-add:disabled { opacity: 0.4; cursor: not-allowed; }\n"
    "\n"
    "  .btn-danger {\n"
    "    background: transparent;\n"
    "    color: var(--danger);\n"
    "    border: 1px solid var(--danger);\n"
    "    padding: 4px 10px;\n"
    "    font-size: 11px;\n"
    "  }\n"
    "  .btn-danger:hover { background: var(--danger); color: #fff; }\n"
    "\n"
    "  .btn-active {\n"
    "    background: transparent;\n"
    "    color: var(--text-muted);\n"
    "    border: 1px solid var(--border);\n"
    "    padding: 4px 10px;\n"
    "    font-size: 11px;\n"
    "  }\n"
    "  .btn-active.is-active {\n"
    "    color: var(--accent);\n"
    "    border-color: var(--accent);\n"
    "  }\n"
    "  .btn-active:hover:not(.is-active) { border-color: var(--accent); color: var(--accent); }\n"
    "\n"
    "  /* ── LOCATION TABLE ── */\n"
    "  .loc-table {\n"
    "    width: 100%;\n"
    "    border-collapse: collapse;\n"
    "    background: var(--bg2);\n"
    "    border: 1px solid var(--border);\n"
    "    border-radius: 6px;\n"
    "    overflow: hidden;\n"
    "  }\n"
    "  .loc-table th {\n"
    "    text-align: left;\n"
    "    padding: 10px 14px;\n"
    "    font-size: 10px;\n"
    "    letter-spacing: 0.1em;\n"
    "    text-transform: uppercase;\n"
    "    color: var(--text-muted);\n"
    "    border-bottom: 1px solid var(--border);\n"
    "    background: var(--bg3);\n"
    "  }\n"
    "  .loc-table td {\n"
    "    padding: 10px 14px;\n"
    "    border-bottom: 1px solid var(--border);\n"
    "    vertical-align: middle;\n"
    "  }\n"
    "  .loc-table tr:last-child td { border-bottom: none; }\n"
    "  .loc-table tr:hover td { background: var(--bg3); }\n"
    "\n"
    "  .loc-name { font-weight: 500; color: var(--text); }\n"
    "  .loc-coord { color: var(--text-muted); font-size: 12px; }\n"
    "\n"
    "  .active-dot {\n"
    "    display: inline-block;\n"
    "    width: 7px; height: 7px;\n"
    "    border-radius: 50%;\n"
    "    background: var(--accent);\n"
    "    margin-right: 6px;\n"
    "    box-shadow: 0 0 6px var(--accent);\n"
    "  }\n"
    "\n"
    "  .geocode-item {\n"
    "    background: var(--bg3);\n"
    "    border: 1px solid var(--border);\n"
    "    border-radius: 4px;\n"
    "    padding: 10px 14px;\n"
    "    margin-bottom: 6px;\n"
    "    cursor: pointer;\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    justify-content: space-between;\n"
    "    transition: border-color 0.15s;\n"
    "  }\n"
    "  .geocode-item:hover { border-color: var(--accent); }\n"
    "  .geocode-item-name { font-weight: 500; }\n"
    "  .geocode-item-meta { font-size: 11px; color: var(--text-muted); }\n"
    "  .geocode-item-coords { font-size: 11px; color: var(--text-muted); margin-top: 2px; }\n"
    "\n"
    "  .empty-state {\n"
    "    text-align: center;\n"
    "    padding: 32px;\n"
    "    color: var(--text-muted);\n"
    "    font-size: 12px;\n"
    "  }\n"
    "\n"
    "  /* ── COMPARE SECTION ── */\n"
    "  #compare-section { margin-top: 8px; }\n"
    "\n"
    "  .compare-controls {\n"
    "    display: grid;\n"
    "    grid-template-columns: 1fr 1fr auto;\n"
    "    gap: 8px;\n"
    "    margin-bottom: 20px;\n"
    "    align-items: end;\n"
    "  }\n"
    "  @media (max-width: 600px) {\n"
    "    .compare-controls { grid-template-columns: 1fr 1fr; }\n"
    "    .compare-controls .btn-compare { grid-column: 1 / -1; }\n"
    "  }\n"
    "\n"
    "  select {\n"
    "    background: var(--bg2);\n"
    "    border: 1px solid var(--border);\n"
    "    color: var(--text);\n"
    "    font-family: var(--mono);\n"
    "    font-size: 13px;\n"
    "    padding: 8px 12px;\n"
    "    border-radius: 4px;\n"
    "    outline: none;\n"
    "    cursor: pointer;\n"
    "    width: 100%;\n"
    "  }\n"
    "  select:focus { border-color: var(--accent); }\n"
    "\n"
    "  .ctrl-label {\n"
    "    font-size: 10px;\n"
    "    letter-spacing: 0.1em;\n"
    "    text-transform: uppercase;\n"
    "    color: var(--text-muted);\n"
    "    margin-bottom: 6px;\n"
    "  }\n"
    "\n"
    "  .btn-compare {\n"
    "    background: var(--accent);\n"
    "    color: var(--bg);\n"
    "    align-self: flex-end;\n"
    "  }\n"
    "  .btn-compare:hover { background: var(--accent2); }\n"
    "  .btn-compare:disabled { opacity: 0.4; cursor: not-allowed; }\n"
    "\n"
    "  /* ── WEATHER CARDS ── */\n"
    "  .compare-grid {\n"
    "    display: grid;\n"
    "    grid-template-columns: 1fr 1fr;\n"
    "    gap: 16px;\n"
    "  }\n"
    "  @media (max-width: 680px) {\n"
    "    .compare-grid { grid-template-columns: 1fr; }\n"
    "  }\n"
    "\n"
    "  .weather-card {\n"
    "    background: var(--bg2);\n"
    "    border: 1px solid var(--border);\n"
    "    border-radius: 6px;\n"
    "    overflow: hidden;\n"
    "    min-height: 200px;\n"
    "  }\n"
    "\n"
    "  .card-header {\n"
    "    background: var(--bg3);\n"
    "    border-bottom: 1px solid var(--border);\n"
    "    padding: 12px 16px;\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    justify-content: space-between;\n"
    "  }\n"
    "  .card-title {\n"
    "    font-family: var(--display);\n"
    "    font-size: 16px;\n"
    "    font-weight: 700;\n"
    "    color: var(--accent);\n"
    "  }\n"
    "  .card-slot {\n"
    "    font-size: 10px;\n"
    "    letter-spacing: 0.1em;\n"
    "    text-transform: uppercase;\n"
    "    color: var(--text-muted);\n"
    "  }\n"
    "\n"
    "  .card-body { padding: 16px; }\n"
    "\n"
    "  .card-placeholder {\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    justify-content: center;\n"
    "    min-height: 140px;\n"
    "    color: var(--text-muted);\n"
    "    font-size: 12px;\n"
    "    flex-direction: column;\n"
    "    gap: 8px;\n"
    "  }\n"
    "  .card-placeholder .icon { font-size: 28px; opacity: 0.3; }\n"
    "\n"
    "  .weather-main {\n"
    "    display: flex;\n"
    "    align-items: flex-end;\n"
    "    gap: 12px;\n"
    "    margin-bottom: 16px;\n"
    "  }\n"
    "  .weather-temp {\n"
    "    font-family: var(--display);\n"
    "    font-size: 48px;\n"
    "    font-weight: 800;\n"
    "    line-height: 1;\n"
    "    color: var(--text);\n"
    "  }\n"
    "  .weather-temp sup { font-size: 20px; color: var(--text-muted); }\n"
    "  .weather-desc {\n"
    "    font-size: 12px;\n"
    "    color: var(--text-muted);\n"
    "    padding-bottom: 6px;\n"
    "  }\n"
    "\n"
    "  .weather-grid {\n"
    "    display: grid;\n"
    "    grid-template-columns: 1fr 1fr;\n"
    "    gap: 8px;\n"
    "  }\n"
    "  .weather-row {\n"
    "    background: var(--bg3);\n"
    "    border-radius: 4px;\n"
    "    padding: 8px 10px;\n"
    "  }\n"
    "  .wr-label {\n"
    "    font-size: 10px;\n"
    "    letter-spacing: 0.08em;\n"
    "    text-transform: uppercase;\n"
    "    color: var(--text-muted);\n"
    "    margin-bottom: 2px;\n"
    "  }\n"
    "  .wr-value { font-size: 14px; font-weight: 500; }\n"
    "\n"
    "  /* ── FORECAST ── */\n"
    "  .forecast-title {\n"
    "    font-size: 10px;\n"
    "    letter-spacing: 0.1em;\n"
    "    text-transform: uppercase;\n"
    "    color: var(--text-muted);\n"
    "    margin: 16px 0 8px;\n"
    "  }\n"
    "  .forecast-row {\n"
    "    display: flex;\n"
    "    gap: 6px;\n"
    "    overflow-x: auto;\n"
    "    padding-bottom: 4px;\n"
    "  }\n"
    "  .forecast-day {\n"
    "    background: var(--bg3);\n"
    "    border-radius: 4px;\n"
    "    padding: 8px 10px;\n"
    "    min-width: 64px;\n"
    "    text-align: center;\n"
    "    flex-shrink: 0;\n"
    "  }\n"
    "  .fd-day { font-size: 10px; color: var(--text-muted); margin-bottom: 4px; }\n"
    "  .fd-max { font-size: 14px; font-weight: 500; }\n"
    "  .fd-min { font-size: 11px; color: var(--text-muted); }\n"
    "\n"
    "  /* ── SPINNER ── */\n"
    "  .spinner {\n"
    "    width: 20px; height: 20px;\n"
    "    border: 2px solid var(--border);\n"
    "    border-top-color: var(--accent);\n"
    "    border-radius: 50%;\n"
    "    animation: spin 0.7s linear infinite;\n"
    "    margin: 0 auto;\n"
    "  }\n"
    "  @keyframes spin { to { transform: rotate(360deg); } }\n"
    "\n"
    "  /* ── TOAST ── */\n"
    "  #toast {\n"
    "    position: fixed;\n"
    "    bottom: 24px;\n"
    "    left: 50%;\n"
    "    transform: translateX(-50%) translateY(80px);\n"
    "    background: var(--bg3);\n"
    "    border: 1px solid var(--border);\n"
    "    border-radius: 6px;\n"
    "    padding: 10px 20px;\n"
    "    font-size: 12px;\n"
    "    transition: transform 0.3s;\n"
    "    z-index: 999;\n"
    "    pointer-events: none;\n"
    "  }\n"
    "  #toast.show { transform: translateX(-50%) translateY(0); }\n"
    "  #toast.ok { border-color: var(--accent); color: var(--accent); }\n"
    "  #toast.err { border-color: var(--danger); color: var(--danger); }\n"
    "\n"
    "  /* ── STATUS BAR ── */\n"
    "  .status-bar {\n"
    "    font-size: 10px;\n"
    "    color: var(--text-muted);\n"
    "    letter-spacing: 0.05em;\n"
    "    padding: 8px 24px;\n"
    "    border-top: 1px solid var(--border);\n"
    "    background: var(--bg2);\n"
    "    position: fixed;\n"
    "    bottom: 0; left: 0; right: 0;\n"
    "    display: flex;\n"
    "    gap: 16px;\n"
    "  }\n"
    "  .status-dot {\n"
    "    display: inline-block;\n"
    "    width: 6px; height: 6px;\n"
    "    border-radius: 50%;\n"
    "    background: var(--accent);\n"
    "    margin-right: 5px;\n"
    "    animation: pulse 2s ease-in-out infinite;\n"
    "  }\n"
    "  @keyframes pulse {\n"
    "    0%, 100% { opacity: 1; }\n"
    "    50% { opacity: 0.3; }\n"
    "  }\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<header>\n"
    "      <div class=\"logo\">\n"
    "    <svg width=\"449\" height=\"207\" viewBox=\"0 0 449 207\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"
    "<path d=\"M63.5983 205.5H0.598328L37.5983 0.5H98.5983L86.5983 69.5H87.5983L166.598 0.5H240.598L134.598 96.5V98L241.598 205.5H157.598L78.5983 123.5H77.5983L63.5983 205.5Z\" fill=\"white\" stroke=\"#A3A1A3\"/>\n"
    "<path d=\"M448.598 205.5V206.5L357.598 205.5L303.598 152.5V151.5H389.598L448.598 205.5Z\" fill=\"#3677DB\"/>\n"
    "<path d=\"M250.598 98.5L264.598 112.5L262.598 113.5L238.598 134.5H209.598L250.598 98.5Z\" fill=\"#3A7ADA\"/>\n"
    "<path d=\"M171.598 98.5L208.598 135.5L250.598 98.5L300.598 54.5H378.598L438.598 0.5H279.598L229.598 45.5L199.598 72.5L188.598 81.5L171.598 97.5V98.5Z\" fill=\"url(#paint0_linear_6_165)\"/>\n"
    "<path d=\"M209.598 134.5L208.598 135.5L279.598 205.5H357.598L303.598 152.5V151.5L264.598 112.5L262.598 113.5L238.598 134.5H209.598Z\" fill=\"url(#paint1_linear_6_165)\"/>\n"
    "<defs>\n"
    "<linearGradient id=\"paint0_linear_6_165\" x1=\"305.098\" y1=\"0.5\" x2=\"305.098\" y2=\"135.5\" gradientUnits=\"userSpaceOnUse\">\n"
    "<stop stop-color=\"#408CDE\"/>\n"
    "<stop offset=\"1\" stop-color=\"#58B2E9\"/>\n"
    "</linearGradient>\n"
    "<linearGradient id=\"paint1_linear_6_165\" x1=\"283.098\" y1=\"112.5\" x2=\"283.098\" y2=\"205.5\" gradientUnits=\"userSpaceOnUse\">\n"
    "<stop stop-color=\"#52AAE7\"/>\n"
    "<stop offset=\"1\" stop-color=\"#479FE5\"/>\n"
    "</linearGradient>\n"
    "</defs>\n"
    "</svg>\n"
    "  </div>\n"
    "  <div class=\"header-right\">\n"
    "    <a href=\"/\" class=\"back-link\" id=\"lnk-back\">← Portal</a>\n"
    "    <div class=\"lang-toggle\">\n"
    "      <button class=\"lang-btn active\" onclick=\"setLang('de')\">DE</button>\n"
    "      <button class=\"lang-btn\" onclick=\"setLang('en')\">EN</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</header>\n"
    "\n"
    "<main>\n"
    "  <!-- COMPARE -->\n"
    "  <section id=\"compare-section\">\n"
    "    <div class=\"section-label\" id=\"lbl-compare\">Wettervergleich</div>\n"
    "\n"
    "    <div class=\"compare-controls\">\n"
    "      <div>\n"
    "        <div class=\"ctrl-label\" id=\"lbl-locA\">Ort A</div>\n"
    "        <select id=\"sel-a\"></select>\n"
    "      </div>\n"
    "      <div>\n"
    "        <div class=\"ctrl-label\" id=\"lbl-locB\">Ort B</div>\n"
    "        <select id=\"sel-b\"></select>\n"
    "      </div>\n"
    "      <button class=\"btn btn-compare\" id=\"btn-compare\" onclick=\"loadWeather()\">\n"
    "        ↻ <span id=\"lbl-refresh\">Aktualisieren</span>\n"
    "      </button>\n"
    "    </div>\n"
    "\n"
    "    <div class=\"compare-grid\">\n"
    "      <div class=\"weather-card\" id=\"card-a\">\n"
    "        <div class=\"card-header\">\n"
    "          <span class=\"card-title\" id=\"card-a-title\">—</span>\n"
    "          <span class=\"card-slot\" id=\"lbl-slot-a\">ORT A</span>\n"
    "        </div>\n"
    "        <div class=\"card-body\">\n"
    "          <div class=\"card-placeholder\" id=\"ph-a\">\n"
    "            <div class=\"icon\">◎</div>\n"
    "            <span id=\"ph-a-text\">Ort wählen und aktualisieren</span>\n"
    "          </div>\n"
    "          <div id=\"weather-a\" style=\"display:none\"></div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div class=\"weather-card\" id=\"card-b\">\n"
    "        <div class=\"card-header\">\n"
    "          <span class=\"card-title\" id=\"card-b-title\">—</span>\n"
    "          <span class=\"card-slot\" id=\"lbl-slot-b\">ORT B</span>\n"
    "        </div>\n"
    "        <div class=\"card-body\">\n"
    "          <div class=\"card-placeholder\" id=\"ph-b\">\n"
    "            <div class=\"icon\">◎</div>\n"
    "            <span id=\"ph-b-text\">Ort wählen und aktualisieren</span>\n"
    "          </div>\n"
    "          <div id=\"weather-b\" style=\"display:none\"></div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </section>\n"
    "\n"
    "  <!-- MANAGEMENT -->\n"
    "  <section id=\"mgmt-section\" style=\"margin-top:36px\">\n"
    "    <div class=\"section-label\" id=\"lbl-manage\">Orte verwalten</div>\n"
    "\n"
    "    <div class=\"add-form\" style=\"grid-template-columns: 1fr auto\">\n"
    "      <input type=\"text\" id=\"inp-name\" placeholder=\"Name\" maxlength=\"63\" autocomplete=\"off\" spellcheck=\"false\">\n"
    "      <button class=\"btn btn-add\" id=\"btn-add\" onclick=\"searchLocation()\">⌕ <span id=\"lbl-add\">Suchen</span></button>\n"
    "    </div>\n"
    "    <div id=\"geocode-dropdown\" style=\"display:none;margin-bottom:12px;\">\n"
    "      <div class=\"ctrl-label\" id=\"lbl-select-result\" style=\"margin-bottom:6px;\">Ort auswählen</div>\n"
    "      <div id=\"geocode-results\"></div>\n"
    "    </div>\n"
    "\n"
    "    <div id=\"loc-list-wrap\">\n"
    "      <table class=\"loc-table\" id=\"loc-table\">\n"
    "        <thead>\n"
    "          <tr>\n"
    "            <th id=\"th-name\">Name</th>\n"
    "            <th id=\"th-coords\">Koordinaten</th>\n"
    "            <th id=\"th-status\">Status</th>\n"
    "            <th></th>\n"
    "          </tr>\n"
    "        </thead>\n"
    "        <tbody id=\"loc-tbody\"></tbody>\n"
    "      </table>\n"
    "    </div>\n"
    "  </section>\n"
    "</main>\n"
    "\n"
    "<div id=\"toast\"></div>\n"
    "\n"
    "<div class=\"status-bar\">\n"
    "  <span><span class=\"status-dot\"></span>ESP32-Core</span>\n"
    "  <span id=\"status-time\"></span>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "// ── I18N ──────────────────────────────────────────────────────────────────\n"
    "const T = {\n"
    "  de: {\n"
    "    title:       'kochcoding // orte',\n"
    "    back:        '← Portal',\n"
    "    manage:      'Orte verwalten',\n"
    "    add:         'Hinzufügen',\n"
    "    compare:     'Ortsvergleich',\n"
    "    locA:        'Ort A',\n"
    "    locB:        'Ort B',\n"
    "    refresh:     'Aktualisieren',\n"
    "    thName:      'Name',\n"
    "    thCoords:    'Koordinaten',\n"
    "    thStatus:    'Status',\n"
    "    active:      'Aktiv',\n"
    "    setActive:   'Aktivieren',\n"
    "    delete:      'Löschen',\n"
    "    slotA:       'ORT A',\n"
    "    slotB:       'ORT B',\n"
    "    placeholder: 'Ort wählen und aktualisieren',\n"
    "    empty:       'Keine Orte gespeichert',\n"
    "    errName:     'Name fehlt',\n"
    "    errCoords:   'Koordinaten ungültig',\n"
    "    loading:     'Laden...',\n"
    "    forecast:    '7-Tage Vorhersage',\n"
    "    humidity:    'Luftfeuchte',\n"
    "    wind:        'Wind',\n"
    "    windDir:     'Windrichtung',\n"
    "    feelsLike:   'Gefühlt',\n"
    "    errFetch:    'Wetterdaten nicht verfügbar',\n"
    "    noSelect:    'Bitte Ort wählen',\n"
    "    searching:   'Suche läuft...',\n"
    "    selectResult:'Ort auswählen',\n"
    "    noResults:   'Keine Ergebnisse gefunden',\n"
    "    errSearch:   'Suche fehlgeschlagen',\n"
    "    search:      'Suchen',\n"
    "    added:       'Ort hinzugefügt',\n"
    "    deleted:     'Ort gelöscht',\n"
    "    activated:   'Ort aktiviert',\n"
    "    errAdd:      'Fehler beim Hinzufügen',\n"
    "    errDel:      'Fehler beim Löschen',\n"
    "    errAct:      'Fehler beim Aktivieren',\n"
    "    days:        ['So','Mo','Di','Mi','Do','Fr','Sa'],\n"
    "  },\n"
    "  en: {\n"
    "    title:       'kochcoding // locations',\n"
    "    back:        '← Portal',\n"
    "    manage:      'Manage Locations',\n"
    "    add:         'Add',\n"
    "    compare:     'Location Comparison',\n"
    "    locA:        'Location A',\n"
    "    locB:        'Location B',\n"
    "    refresh:     'Refresh',\n"
    "    thName:      'Name',\n"
    "    thCoords:    'Coordinates',\n"
    "    thStatus:    'Status',\n"
    "    active:      'Active',\n"
    "    setActive:   'Set Active',\n"
    "    delete:      'Delete',\n"
    "    slotA:       'ORT A',\n"
    "    slotB:       'ORT B',\n"
    "    placeholder: 'Select location and refresh',\n"
    "    empty:       'No locations stored',\n"
    "    errName:     'Name required',\n"
    "    errCoords:   'Invalid coordinates',\n"
    "    loading:     'Loading...',\n"
    "    forecast:    '7-Day Forecast',\n"
    "    humidity:    'Humidity',\n"
    "    wind:        'Wind',\n"
    "    windDir:     'Wind Dir',\n"
    "    feelsLike:   'Feels Like',\n"
    "    errFetch:    'Weather data unavailable',\n"
    "    noSelect:    'Please select a location',\n"
    "    searching:   'Searching...',\n"
    "    selectResult:'Select location',\n"
    "    noResults:   'No results found',\n"
    "    errSearch:   'Search failed',\n"
    "    search:      'Search',\n"
    "    added:       'Location added',\n"
    "    deleted:     'Location deleted',\n"
    "    activated:   'Location activated',\n"
    "    errAdd:      'Error adding location',\n"
    "    errDel:      'Error deleting location',\n"
    "    errAct:      'Error activating location',\n"
    "    days:        ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],\n"
    "  }\n"
    "};\n"
    "\n"
    "let lang = 'de';\n"
    "\n"
    "function setLang(l) {\n"
    "  lang = l;\n"
    "  localStorage.setItem('kc_lang', l);\n"
    "  document.querySelectorAll('.lang-btn').forEach(b => b.classList.toggle('active', b.textContent === l.toUpperCase()));\n"
    "  applyLang();\n"
    "}\n"
    "\n"
    "function t(k) { return T[lang][k] || k; }\n"
    "\n"
    "function applyLang() {\n"
    "  document.title = t('title');\n"
    "  document.getElementById('lnk-back').textContent = t('back');\n"
    "  document.getElementById('lbl-manage').childNodes[0].textContent = t('manage');\n"
    "  document.getElementById('lbl-add').textContent = t('search');\n"
    "  document.getElementById('lbl-select-result').textContent = t('selectResult');\n"
    "  document.getElementById('lbl-compare').childNodes[0].textContent = t('compare');\n"
    "  document.getElementById('lbl-locA').textContent = t('locA');\n"
    "  document.getElementById('lbl-locB').textContent = t('locB');\n"
    "  document.getElementById('lbl-refresh').textContent = t('refresh');\n"
    "  document.getElementById('th-name').textContent = t('thName');\n"
    "  document.getElementById('th-coords').textContent = t('thCoords');\n"
    "  document.getElementById('th-status').textContent = t('thStatus');\n"
    "  document.getElementById('lbl-slot-a').textContent = t('slotA');\n"
    "  document.getElementById('lbl-slot-b').textContent = t('slotB');\n"
    "  document.getElementById('ph-a-text').textContent = t('placeholder');\n"
    "  document.getElementById('ph-b-text').textContent = t('placeholder');\n"
    "  renderLocations();\n"
    "}\n"
    "\n"
    "// ── STATE ─────────────────────────────────────────────────────────────────\n"
    "let locations = [];\n"
    "\n"
    "// ── API ───────────────────────────────────────────────────────────────────\n"
    "async function apiGet(url) {\n"
    "  const r = await fetch(url);\n"
    "  return r.json();\n"
    "}\n"
    "\n"
    "async function apiPost(url, body) {\n"
    "  const r = await fetch(url, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(body) });\n"
    "  return r.json();\n"
    "}\n"
    "\n"
    "async function apiDelete(url) {\n"
    "  const r = await fetch(url, { method: 'DELETE' });\n"
    "  return r.json();\n"
    "}\n"
    "\n"
    "async function apiPut(url) {\n"
    "  const r = await fetch(url, { method: 'PUT' });\n"
    "  return r.json();\n"
    "}\n"
    "\n"
    "// ── TOAST ─────────────────────────────────────────────────────────────────\n"
    "let toastTimer;\n"
    "function toast(msg, type = 'ok') {\n"
    "  const el = document.getElementById('toast');\n"
    "  el.textContent = msg;\n"
    "  el.className = 'show ' + type;\n"
    "  clearTimeout(toastTimer);\n"
    "  toastTimer = setTimeout(() => { el.className = ''; }, 2500);\n"
    "}\n"
    "\n"
    "// ── LOCATIONS ─────────────────────────────────────────────────────────────\n"
    "async function loadLocations() {\n"
    "  try {\n"
    "    const d = await apiGet('/api/locations');\n"
    "    locations = d.locations || [];\n"
    "    renderLocations();\n"
    "    updateSelects();\n"
    "  } catch(e) {\n"
    "    locations = [];\n"
    "    renderLocations();\n"
    "  }\n"
    "}\n"
    "\n"
    "function renderLocations() {\n"
    "  const tbody = document.getElementById('loc-tbody');\n"
    "  if (locations.length === 0) {\n"
    "    tbody.innerHTML = `<tr><td colspan=\"4\"><div class=\"empty-state\">${t('empty')}</div></td></tr>`;\n"
    "    return;\n"
    "  }\n"
    "  tbody.innerHTML = locations.map(loc => `\n"
    "    <tr>\n"
    "      <td><span class=\"loc-name\">${loc.is_active ? '<span class=\"active-dot\"></span>' : ''}${esc(loc.name)}</span></td>\n"
    "      <td><span class=\"loc-coord\">${loc.latitude.toFixed(4)}, ${loc.longitude.toFixed(4)}</span></td>\n"
    "      <td>\n"
    "        <button class=\"btn btn-active ${loc.is_active ? 'is-active' : ''}\"\n"
    "          onclick=\"setActive('${esc(loc.name)}')\" ${loc.is_active ? 'disabled' : ''}>\n"
    "          ${loc.is_active ? t('active') : t('setActive')}\n"
    "        </button>\n"
    "      </td>\n"
    "      <td>\n"
    "        <button class=\"btn btn-danger\" onclick=\"deleteLocation('${esc(loc.name)}')\">${t('delete')}</button>\n"
    "      </td>\n"
    "    </tr>\n"
    "  `).join('');\n"
    "}\n"
    "\n"
    "function updateSelects() {\n"
    "  const names = locations.map(l => l.name);\n"
    "  const selA = document.getElementById('sel-a');\n"
    "  const selB = document.getElementById('sel-b');\n"
    "  const prevA = selA.value;\n"
    "  const prevB = selB.value;\n"
    "\n"
    "  const opts = names.map(n => `<option value=\"${esc(n)}\">${esc(n)}</option>`).join('');\n"
    "  const empty = `<option value=\"\">—</option>`;\n"
    "  selA.innerHTML = empty + opts;\n"
    "  selB.innerHTML = empty + opts;\n"
    "\n"
    "  if (names.includes(prevA)) selA.value = prevA;\n"
    "  if (names.includes(prevB)) selB.value = prevB;\n"
    "}\n"
    "\n"
    "async function searchLocation() {\n"
    "  const name = document.getElementById('inp-name').value.trim();\n"
    "  if (!name) { toast(t('errName'), 'err'); return; }\n"
    "\n"
    "  const btn = document.getElementById('btn-add');\n"
    "  const dropdown = document.getElementById('geocode-dropdown');\n"
    "  const resultsEl = document.getElementById('geocode-results');\n"
    "\n"
    "  btn.disabled = true;\n"
    "  dropdown.style.display = 'none';\n"
    "  resultsEl.innerHTML = `<div class=\"card-placeholder\"><div class=\"spinner\"></div><span>${t('searching')}</span></div>`;\n"
    "  dropdown.style.display = 'block';\n"
    "\n"
    "  try {\n"
    "    const r = await apiGet(`/api/geocode?name=${encodeURIComponent(name)}`);\n"
    "    if (!r.results || r.results.length === 0) {\n"
    "      resultsEl.innerHTML = `<div class=\"empty-state\">${t('noResults')}</div>`;\n"
    "      btn.disabled = false;\n"
    "      return;\n"
    "    }\n"
    "    resultsEl.innerHTML = r.results.map((item, i) => `\n"
    "      <div class=\"geocode-item\" onclick=\"confirmLocation(${i})\">\n"
    "        <div>\n"
    "          <div class=\"geocode-item-name\">${esc(item.name)}</div>\n"
    "          <div class=\"geocode-item-coords\">${item.latitude.toFixed(4)}, ${item.longitude.toFixed(4)}</div>\n"
    "        </div>\n"
    "        <div class=\"geocode-item-meta\">${esc(item.admin1 || '')}${item.admin1 && item.country_code ? ' · ' : ''}${esc(item.country_code || '')}</div>\n"
    "      </div>\n"
    "    `).join('');\n"
    "    window._geocodeResults = r.results;\n"
    "  } catch(e) {\n"
    "    resultsEl.innerHTML = `<div class=\"empty-state\">${t('errSearch')}</div>`;\n"
    "  }\n"
    "  btn.disabled = false;\n"
    "}\n"
    "\n"
    "async function confirmLocation(idx) {\n"
    "  const item = window._geocodeResults[idx];\n"
    "  if (!item) return;\n"
    "\n"
    "  document.getElementById('geocode-dropdown').style.display = 'none';\n"
    "  document.getElementById('inp-name').value = '';\n"
    "  window._geocodeResults = [];\n"
    "\n"
    "  try {\n"
    "    const r = await apiPost('/api/locations', {\n"
    "      name: item.name,\n"
    "      latitude: item.latitude,\n"
    "      longitude: item.longitude\n"
    "    });\n"
    "    if (r.ok) {\n"
    "      toast(t('added'));\n"
    "      await loadLocations();\n"
    "    } else {\n"
    "      toast(t('errAdd') + ': ' + (r.error || ''), 'err');\n"
    "    }\n"
    "  } catch(e) { toast(t('errAdd'), 'err'); }\n"
    "}\n"
    "\n"
    "async function deleteLocation(name) {\n"
    "  try {\n"
    "    const r = await apiDelete(`/api/locations?name=${encodeURIComponent(name)}`);\n"
    "    if (r.ok) { toast(t('deleted')); await loadLocations(); }\n"
    "    else toast(t('errDel') + ': ' + (r.error || ''), 'err');\n"
    "  } catch(e) { toast(t('errDel'), 'err'); }\n"
    "}\n"
    "\n"
    "async function setActive(name) {\n"
    "  try {\n"
    "    const r = await apiPut(`/api/locations/active?name=${encodeURIComponent(name)}`);\n"
    "    if (r.ok) { toast(t('activated')); await loadLocations(); }\n"
    "    else toast(t('errAct') + ': ' + (r.error || ''), 'err');\n"
    "  } catch(e) { toast(t('errAct'), 'err'); }\n"
    "}\n"
    "\n"
    "// ── WEATHER ───────────────────────────────────────────────────────────────\n"
    "function wmoDescription(code) {\n"
    "  const m = {\n"
    "    0:'☀️ Clear',1:'🌤 Mostly Clear',2:'⛅ Partly Cloudy',3:'☁️ Overcast',\n"
    "    45:'🌫 Foggy',48:'🌫 Icy Fog',\n"
    "    51:'🌦 Light Drizzle',53:'🌦 Drizzle',55:'🌧 Heavy Drizzle',\n"
    "    61:'🌧 Light Rain',63:'🌧 Rain',65:'🌧 Heavy Rain',\n"
    "    71:'🌨 Light Snow',73:'🌨 Snow',75:'❄️ Heavy Snow',\n"
    "    80:'🌦 Showers',81:'🌧 Heavy Showers',82:'⛈ Violent Showers',\n"
    "    95:'⛈ Thunderstorm',96:'⛈ Hail Storm',99:'⛈ Heavy Hail Storm',\n"
    "  };\n"
    "  return m[code] || `Code ${code}`;\n"
    "}\n"
    "\n"
    "function windDirLabel(deg) {\n"
    "  const dirs = ['N','NE','E','SE','S','SW','W','NW'];\n"
    "  return dirs[Math.round(deg / 45) % 8];\n"
    "}\n"
    "\n"
    "function renderWeather(slot, name, currentData, forecastData) {\n"
    "  const card = document.getElementById(`card-${slot}`);\n"
    "  const ph   = document.getElementById(`ph-${slot}`);\n"
    "  const wd   = document.getElementById(`weather-${slot}`);\n"
    "  const title = document.getElementById(`card-${slot}-title`);\n"
    "\n"
    "  title.textContent = name;\n"
    "\n"
    "  if (!currentData) {\n"
    "    ph.style.display = 'flex';\n"
    "    ph.querySelector('span').textContent = t('errFetch');\n"
    "    wd.style.display = 'none';\n"
    "    return;\n"
    "  }\n"
    "\n"
    "  const c = currentData.current || {};\n"
    "  const temp  = c.temperature_2m;\n"
    "  const feels = c.apparent_temperature;\n"
    "  const hum   = c.relative_humidity_2m;\n"
    "  const wspd  = c.wind_speed_10m;\n"
    "  const wdir  = c.wind_direction_10m;\n"
    "  const wcode = c.weather_code;\n"
    "\n"
    "  let forecastHTML = '';\n"
    "  if (forecastData && forecastData.daily) {\n"
    "    const d = forecastData.daily;\n"
    "    const days = d.time || [];\n"
    "    forecastHTML = `\n"
    "      <div class=\"forecast-title\">${t('forecast')}</div>\n"
    "      <div class=\"forecast-row\">\n"
    "        ${days.slice(0,7).map((dateStr, i) => {\n"
    "          const dow = new Date(dateStr).getDay();\n"
    "          return `<div class=\"forecast-day\">\n"
    "            <div class=\"fd-day\">${t('days')[dow]}</div>\n"
    "            <div class=\"fd-max\">${Math.round(d.temperature_2m_max[i])}°</div>\n"
    "            <div class=\"fd-min\">${Math.round(d.temperature_2m_min[i])}°</div>\n"
    "          </div>`;\n"
    "        }).join('')}\n"
    "      </div>`;\n"
    "  }\n"
    "\n"
    "  wd.innerHTML = `\n"
    "    <div class=\"weather-main\">\n"
    "      <div class=\"weather-temp\">${Math.round(temp)}<sup>°C</sup></div>\n"
    "      <div class=\"weather-desc\">${wmoDescription(wcode)}</div>\n"
    "    </div>\n"
    "    <div class=\"weather-grid\">\n"
    "      <div class=\"weather-row\">\n"
    "        <div class=\"wr-label\">${t('feelsLike')}</div>\n"
    "        <div class=\"wr-value\">${Math.round(feels)}°C</div>\n"
    "      </div>\n"
    "      <div class=\"weather-row\">\n"
    "        <div class=\"wr-label\">${t('humidity')}</div>\n"
    "        <div class=\"wr-value\">${hum}%</div>\n"
    "      </div>\n"
    "      <div class=\"weather-row\">\n"
    "        <div class=\"wr-label\">${t('wind')}</div>\n"
    "        <div class=\"wr-value\">${Math.round(wspd)} km/h</div>\n"
    "      </div>\n"
    "      <div class=\"weather-row\">\n"
    "        <div class=\"wr-label\">${t('windDir')}</div>\n"
    "        <div class=\"wr-value\">${windDirLabel(wdir)} (${Math.round(wdir)}°)</div>\n"
    "      </div>\n"
    "    </div>\n"
    "    ${forecastHTML}\n"
    "  `;\n"
    "\n"
    "  ph.style.display = 'none';\n"
    "  wd.style.display = 'block';\n"
    "}\n"
    "\n"
    "function showLoading(slot) {\n"
    "  const ph  = document.getElementById(`ph-${slot}`);\n"
    "  const wd  = document.getElementById(`weather-${slot}`);\n"
    "  const ttl = document.getElementById(`card-${slot}-title`);\n"
    "  ph.innerHTML = `<div class=\"spinner\"></div><span>${t('loading')}</span>`;\n"
    "  ph.style.display = 'flex';\n"
    "  wd.style.display = 'none';\n"
    "  ttl.textContent = '—';\n"
    "}\n"
    "\n"
    "async function loadWeather() {\n"
    "  const nameA = document.getElementById('sel-a').value;\n"
    "  const nameB = document.getElementById('sel-b').value;\n"
    "\n"
    "  if (!nameA && !nameB) { toast(t('noSelect'), 'err'); return; }\n"
    "\n"
    "  const btn = document.getElementById('btn-compare');\n"
    "  btn.disabled = true;\n"
    "\n"
    "  async function fetchSlot(slot, name) {\n"
    "    if (!name) return;\n"
    "    showLoading(slot);\n"
    "    const MAX_ATTEMPTS = 3;\n"
    "    for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {\n"
    "      try {\n"
    "        const [cur, fore] = await Promise.all([\n"
    "          apiGet(`/api/weather/current?name=${encodeURIComponent(name)}`),\n"
    "          apiGet(`/api/weather/forecast?name=${encodeURIComponent(name)}`)\n"
    "        ]);\n"
    "        renderWeather(slot, name, cur.ok !== false ? cur : null, fore.ok !== false ? fore : null);\n"
    "        return;\n"
    "      } catch(e) {\n"
    "        if (attempt < MAX_ATTEMPTS) {\n"
    "          await new Promise(r => setTimeout(r, 1500));\n"
    "        } else {\n"
    "          const ph  = document.getElementById(`ph-${slot}`);\n"
    "          const wd  = document.getElementById(`weather-${slot}`);\n"
    "          const ttl = document.getElementById(`card-${slot}-title`);\n"
    "          ttl.textContent = name;\n"
    "          ph.innerHTML = `<div class=\"icon\">◎</div><span>${t('errFetch')}</span>`;\n"
    "          ph.style.display = 'flex';\n"
    "          wd.style.display = 'none';\n"
    "        }\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "\n"
    "  await Promise.all([fetchSlot('a', nameA), fetchSlot('b', nameB)]);\n"
    "  btn.disabled = false;\n"
    "}\n"
    "\n"
    "// ── STATUS CLOCK ──────────────────────────────────────────────────────────\n"
    "function esc(s) {\n"
    "  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');\n"
    "}\n"
    "\n"
    "function updateClock() {\n"
    "  const now = new Date();\n"
    "  document.getElementById('status-time').textContent =\n"
    "    now.toLocaleTimeString(lang === 'de' ? 'de-DE' : 'en-US');\n"
    "}\n"
    "setInterval(updateClock, 1000);\n"
    "updateClock();\n"
    "\n"
    "// ── INIT ──────────────────────────────────────────────────────────────────\n"
    "(function() {\n"
    "  var saved = localStorage.getItem('kc_lang');\n"
    "  if (saved === 'de' || saved === 'en') { lang = saved; }\n"
    "  setLang(lang);\n"
    "})();\n"
    "loadLocations();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "\n";
// clang-format on
