#include "ui/ui_assets.h"

// clang-format off
const char UI_INDEX_HTML[] =
    "<!doctype html>\n"
    "<html lang=\"de\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<title>ESP32 Setup \xe2\x80\x94 kochcoding</title>\n"
    "<style>\n"
    "  @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Sora:wght@300;400;600;700&display=swap');\n"
    "  :root {\n"
    "    --blue-primary: #367EDA;\n"
    "    --blue-light: #58B2E9;\n"
    "    --blue-mid: #408CDE;\n"
    "    --blue-accent: #52AAE7;\n"
    "    --bg-deep: #0d0f14;\n"
    "    --bg-card: #13161d;\n"
    "    --bg-input: #1a1e28;\n"
    "    --border: rgba(54,126,218,0.18);\n"
    "    --text-primary: #f0f2f7;\n"
    "    --text-muted: #6b7694;\n"
    "    --text-dim: #3d4560;\n"
    "    --success: #3dd68c;\n"
    "    --error: #f04f5a;\n"
    "    --warning: #f0a04f;\n"
    "  }\n"
    "  *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n"
    "  html,body{height:100%;background:var(--bg-deep);color:var(--text-primary);font-family:'Sora',sans-serif;-webkit-font-smoothing:antialiased;overflow-x:hidden}\n"
    "  body::before{content:'';position:fixed;inset:0;background-image:linear-gradient(rgba(54,126,218,0.04) 1px,transparent 1px),linear-gradient(90deg,rgba(54,126,218,0.04) 1px,transparent 1px);background-size:40px 40px;pointer-events:none;z-index:0}\n"
    "  body::after{content:'';position:fixed;top:-20%;right:-10%;width:60vw;height:60vw;background:radial-gradient(circle,rgba(54,126,218,0.08) 0%,transparent 70%);pointer-events:none;z-index:0;animation:orb-drift 8s ease-in-out infinite alternate}\n"
    "  @keyframes orb-drift{from{transform:translate(0,0)}to{transform:translate(-5%,5%)}}\n"
    "  .wrapper{position:relative;z-index:1;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:24px 16px}\n"
    "  .header{width:100%;max-width:420px;margin-bottom:28px;display:flex;flex-direction:column;align-items:flex-start;gap:10px;animation:slide-down 0.6s cubic-bezier(0.16,1,0.3,1) both}\n"
    "  @keyframes slide-down{from{opacity:0;transform:translateY(-16px)}to{opacity:1;transform:translateY(0)}}\n"
    "  .logo-svg{width:160px;height:auto;opacity:0.92}\n"
    "  .header-sub{font-size:11px;font-weight:400;letter-spacing:0.18em;text-transform:uppercase;color:var(--text-muted);font-family:'DM Mono',monospace}\n"
    "  .card{width:100%;max-width:420px;background:var(--bg-card);border:1px solid var(--border);border-radius:16px;padding:32px;position:relative;overflow:hidden;animation:slide-up 0.7s cubic-bezier(0.16,1,0.3,1) 0.1s both}\n"
    "  @keyframes slide-up{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}\n"
    "  .card::before{content:'';position:absolute;top:0;left:0;right:0;height:1px;background:linear-gradient(90deg,transparent,var(--blue-primary),var(--blue-light),transparent);opacity:0.7}\n"
    "  .card-title{font-size:18px;font-weight:600;color:var(--text-primary);margin-bottom:4px;letter-spacing:-0.01em}\n"
    "  .card-desc{font-size:13px;color:var(--text-muted);margin-bottom:28px;line-height:1.5}\n"
    "  .field{margin-bottom:16px}\n"
    "  .field label{display:block;font-size:11px;font-weight:600;letter-spacing:0.12em;text-transform:uppercase;color:var(--text-muted);font-family:'DM Mono',monospace;margin-bottom:8px}\n"
    "  .input-wrap{position:relative}\n"
    "  .field input{width:100%;background:var(--bg-input);border:1px solid var(--border);border-radius:10px;padding:13px 16px;font-size:14px;font-family:'DM Mono',monospace;color:var(--text-primary);outline:none;transition:border-color 0.2s,box-shadow 0.2s,background 0.2s;-webkit-appearance:none}\n"
    "  .field input::placeholder{color:var(--text-dim)}\n"
    "  .field input:focus{border-color:var(--blue-primary);box-shadow:0 0 0 3px rgba(54,126,218,0.12);background:#1e2330}\n"
    "  .field input.error{border-color:var(--error);box-shadow:0 0 0 3px rgba(240,79,90,0.1)}\n"
    "  .pass-toggle{position:absolute;right:14px;top:50%;transform:translateY(-50%);background:none;border:none;cursor:pointer;color:var(--text-muted);padding:4px;display:flex;align-items:center;transition:color 0.2s}\n"
    "  .pass-toggle:hover{color:var(--text-primary)}\n"
    "  #pass{padding-right:44px}\n"
    "  .btn-submit{width:100%;margin-top:24px;padding:14px 24px;background:linear-gradient(135deg,var(--blue-primary),var(--blue-mid));border:none;border-radius:10px;color:#fff;font-size:14px;font-weight:600;font-family:'Sora',sans-serif;letter-spacing:0.02em;cursor:pointer;position:relative;overflow:hidden;transition:opacity 0.2s,transform 0.15s,box-shadow 0.2s;box-shadow:0 4px 20px rgba(54,126,218,0.25)}\n"
    "  .btn-submit:hover:not(:disabled){opacity:0.92;transform:translateY(-1px);box-shadow:0 6px 28px rgba(54,126,218,0.35)}\n"
    "  .btn-submit:active:not(:disabled){transform:translateY(0)}\n"
    "  .btn-submit:disabled{opacity:0.5;cursor:not-allowed}\n"
    "  .btn-submit .btn-spinner{display:none}\n"
    "  .btn-submit.loading .btn-text{display:none}\n"
    "  .btn-submit.loading .btn-spinner{display:flex;align-items:center;justify-content:center;gap:8px}\n"
    "  .spinner-dot{width:6px;height:6px;border-radius:50%;background:rgba(255,255,255,0.9);animation:bounce 0.9s ease-in-out infinite}\n"
    "  .spinner-dot:nth-child(2){animation-delay:0.15s}\n"
    "  .spinner-dot:nth-child(3){animation-delay:0.30s}\n"
    "  @keyframes bounce{0%,80%,100%{transform:scale(0.6);opacity:0.4}40%{transform:scale(1);opacity:1}}\n"
    "  .status{margin-top:16px;border-radius:10px;padding:12px 16px;font-size:13px;line-height:1.5;display:none;align-items:flex-start;gap:10px;animation:fade-in 0.3s ease both}\n"
    "  @keyframes fade-in{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:translateY(0)}}\n"
    "  .status.show{display:flex}\n"
    "  .status.success{background:rgba(61,214,140,0.08);border:1px solid rgba(61,214,140,0.25);color:var(--success)}\n"
    "  .status.error{background:rgba(240,79,90,0.08);border:1px solid rgba(240,79,90,0.25);color:var(--error)}\n"
    "  .status.connecting{background:rgba(54,126,218,0.08);border:1px solid rgba(54,126,218,0.25);color:var(--blue-accent)}\n"
    "  .status-icon{flex-shrink:0;margin-top:1px}\n"
    "  .sta-status{margin-top:20px;padding-top:20px;border-top:1px solid var(--border);display:flex;align-items:center;gap:10px;font-size:12px;color:var(--text-muted);font-family:'DM Mono',monospace}\n"
    "  .sta-dot{width:7px;height:7px;border-radius:50%;flex-shrink:0;background:var(--text-dim)}\n"
    "  .sta-dot.connected{background:var(--success);box-shadow:0 0 6px var(--success)}\n"
    "  .sta-dot.connecting{background:var(--warning);animation:pulse 1.2s ease-in-out infinite}\n"
    "  .sta-dot.failed{background:var(--error)}\n"
    "  @keyframes pulse{0%,100%{opacity:1}50%{opacity:0.3}}\n"
    "  .footer{margin-top:24px;font-size:11px;color:var(--text-dim);font-family:'DM Mono',monospace;text-align:center;letter-spacing:0.05em;animation:slide-up 0.7s cubic-bezier(0.16,1,0.3,1) 0.25s both}\n"
    "  @media(max-width:480px){.card{padding:24px 20px;border-radius:12px}.card-title{font-size:16px}}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"wrapper\">\n"
    "  <div class=\"header\">\n"
    "    <svg class=\"logo-svg\" viewBox=\"0 0 449 207\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"
    "      <path d=\"M63.5983 205.5H0.598328L37.5983 0.5H98.5983L86.5983 69.5H87.5983L166.598 0.5H240.598L134.598 96.5V98L241.598 205.5H157.598L78.5983 123.5H77.5983L63.5983 205.5Z\" fill=\"white\" stroke=\"#A3A1A3\"/>\n"
    "      <path d=\"M448.598 205.5V206.5L357.598 205.5L303.598 152.5V151.5H389.598L448.598 205.5Z\" fill=\"#3677DB\"/>\n"
    "      <path d=\"M250.598 98.5L264.598 112.5L262.598 113.5L238.598 134.5H209.598L250.598 98.5Z\" fill=\"#3A7ADA\"/>\n"
    "      <path d=\"M171.598 98.5L208.598 135.5L250.598 98.5L300.598 54.5H378.598L438.598 0.5H279.598L229.598 45.5L199.598 72.5L188.598 81.5L171.598 97.5V98.5Z\" fill=\"url(#sg0)\"/>\n"
    "      <path d=\"M209.598 134.5L208.598 135.5L279.598 205.5H357.598L303.598 152.5V151.5L264.598 112.5L262.598 113.5L238.598 134.5H209.598Z\" fill=\"url(#sg1)\"/>\n"
    "      <defs>\n"
    "        <linearGradient id=\"sg0\" x1=\"305.098\" y1=\"0.5\" x2=\"305.098\" y2=\"135.5\" gradientUnits=\"userSpaceOnUse\">\n"
    "          <stop stop-color=\"#408CDE\"/><stop offset=\"1\" stop-color=\"#58B2E9\"/>\n"
    "        </linearGradient>\n"
    "        <linearGradient id=\"sg1\" x1=\"283.098\" y1=\"112.5\" x2=\"283.098\" y2=\"205.5\" gradientUnits=\"userSpaceOnUse\">\n"
    "          <stop stop-color=\"#52AAE7\"/><stop offset=\"1\" stop-color=\"#479FE5\"/>\n"
    "        </linearGradient>\n"
    "      </defs>\n"
    "    </svg>\n"
    "    <span class=\"header-sub\">Device Setup</span>\n"
    "  </div>\n"
    "  <div class=\"card\">\n"
    "    <div class=\"card-title\">WiFi Configuration</div>\n"
    "    <div class=\"card-desc\">Connect your device to a local network to enable cloud features and remote access.</div>\n"
    "    <div class=\"field\">\n"
    "      <label for=\"ssid\">Network Name (SSID)</label>\n"
    "      <input id=\"ssid\" type=\"text\" placeholder=\"Your WiFi network\" maxlength=\"31\" autocomplete=\"off\" autocapitalize=\"none\" spellcheck=\"false\">\n"
    "    </div>\n"
    "    <div class=\"field\">\n"
    "      <label for=\"pass\">Password</label>\n"
    "      <div class=\"input-wrap\">\n"
    "        <input id=\"pass\" type=\"password\" placeholder=\"Network password\" maxlength=\"63\" autocomplete=\"current-password\">\n"
    "        <button class=\"pass-toggle\" type=\"button\" onclick=\"togglePass()\" aria-label=\"Toggle password visibility\">\n"
    "          <svg id=\"eye-icon\" width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
    "            <path d=\"M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z\"/>\n"
    "            <circle cx=\"12\" cy=\"12\" r=\"3\"/>\n"
    "          </svg>\n"
    "        </button>\n"
    "      </div>\n"
    "    </div>\n"
    "    <button class=\"btn-submit\" id=\"btn\" onclick=\"submitWifi()\">\n"
    "      <span class=\"btn-text\">Connect Device</span>\n"
    "      <span class=\"btn-spinner\">\n"
    "        <span class=\"spinner-dot\"></span>\n"
    "        <span class=\"spinner-dot\"></span>\n"
    "        <span class=\"spinner-dot\"></span>\n"
    "      </span>\n"
    "    </button>\n"
    "    <div class=\"status success\" id=\"status-success\">\n"
    "      <span class=\"status-icon\">\n"
    "        <svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"20 6 9 17 4 12\"/></svg>\n"
    "      </span>\n"
    "      <span id=\"status-success-text\">Credentials saved. Connecting to network...</span>\n"
    "    </div>\n"
    "    <div class=\"status error\" id=\"status-error\">\n"
    "      <span class=\"status-icon\">\n"
    "        <svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\"/><line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\"/></svg>\n"
    "      </span>\n"
    "      <span id=\"status-error-text\">An error occurred. Please try again.</span>\n"
    "    </div>\n"
    "    <div class=\"status connecting\" id=\"status-connecting\">\n"
    "      <span class=\"status-icon\">\n"
    "        <svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M1.42 9a16 16 0 0 1 21.16 0\"/><path d=\"M5 12.55a11 11 0 0 1 14.08 0\"/><path d=\"M10.54 15.64a6 6 0 0 1 2.92 0\"/><circle cx=\"12\" cy=\"20\" r=\"1\"/></svg>\n"
    "      </span>\n"
    "      <span>Attempting to connect. This may take a few seconds...</span>\n"
    "    </div>\n"
    "    <div class=\"sta-status\" id=\"sta-status\">\n"
    "      <div class=\"sta-dot\" id=\"sta-dot\"></div>\n"
    "      <span id=\"sta-text\">Checking connection status...</span>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"footer\">ESP32 Core v0.1.0 &nbsp;&middot;&nbsp; kochcoding</div>\n"
    "</div>\n"
    "<script>\n"
    "  function togglePass(){\n"
    "    var i=document.getElementById('pass'),e=document.getElementById('eye-icon'),h=i.type==='password';\n"
    "    i.type=h?'text':'password';\n"
    "    e.innerHTML=h?'<path d=\"M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94\"/><path d=\"M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19\"/><line x1=\"1\" y1=\"1\" x2=\"23\" y2=\"23\"/>':'<path d=\"M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/>';\n"
    "  }\n"
    "  function hideAll(){\n"
    "    ['status-success','status-error','status-connecting'].forEach(function(id){document.getElementById(id).classList.remove('show');});\n"
    "  }\n"
    "  function showStatus(type,msg){\n"
    "    hideAll();\n"
    "    var el=document.getElementById('status-'+type);\n"
    "    if(msg&&type!=='connecting'){document.getElementById('status-'+type+'-text').textContent=msg;}\n"
    "    el.classList.add('show');\n"
    "  }\n"
    "  function updateStaStatus(state,ip){\n"
    "    var dot=document.getElementById('sta-dot'),text=document.getElementById('sta-text');\n"
    "    dot.className='sta-dot';\n"
    "    if(state==='connected'){dot.classList.add('connected');text.textContent='Connected \xc2\xb7 '+(ip||'');}\n"
    "    else if(state==='connecting'){dot.classList.add('connecting');text.textContent='Connecting to network...';}\n"
    "    else if(state==='failed'){dot.classList.add('failed');text.textContent='Connection failed \xe2\x80\x94 check credentials';}\n"
    "    else{text.textContent='Not connected';}\n"
    "  }\n"
    "  function pollStatus(){\n"
    "    fetch('/api/config/wifi')\n"
    "      .then(function(r){return r.json();})\n"
    "      .then(function(d){updateStaStatus(d.sta_state,d.ip);})\n"
    "      .catch(function(){updateStaStatus('idle');});\n"
    "  }\n"
    "  function submitWifi(){\n"
    "    var ssid=document.getElementById('ssid').value.trim();\n"
    "    var pass=document.getElementById('pass').value;\n"
    "    var btn=document.getElementById('btn');\n"
    "    document.getElementById('ssid').classList.remove('error');\n"
    "    if(!ssid){document.getElementById('ssid').classList.add('error');showStatus('error','Please enter a network name (SSID).');return;}\n"
    "    btn.classList.add('loading');btn.disabled=true;\n"
    "    hideAll();showStatus('connecting');\n"
    "    fetch('/api/config/wifi',{\n"
    "      method:'POST',\n"
    "      headers:{'Content-Type':'application/json'},\n"
    "      body:JSON.stringify({ssid:ssid,pass:pass})\n"
    "    })\n"
    "    .then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json();})\n"
    "    .then(function(d){\n"
    "      btn.classList.remove('loading');btn.disabled=false;\n"
    "      if(d.ok){\n"
    "        showStatus('success','Credentials saved. Connecting to \"'+ssid+'\"...');\n"
    "        updateStaStatus('connecting');\n"
    "        setTimeout(pollStatus,3000);setTimeout(pollStatus,6000);setTimeout(pollStatus,10000);\n"
    "      }else{showStatus('error','Device returned an error. Please try again.');}\n"
    "    })\n"
    "    .catch(function(){\n"
    "      btn.classList.remove('loading');btn.disabled=false;\n"
    "      showStatus('error','Could not reach device. Are you connected to ESP32-Core-Setup?');\n"
    "    });\n"
    "  }\n"
    "  document.addEventListener('keydown',function(e){if(e.key==='Enter')submitWifi();});\n"
    "  pollStatus();\n"
    "  setInterval(pollStatus,15000);\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";
// clang-format on
